{% set name = "hatch-jupyter-builder" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_jupyter_builder-{{ version }}.tar.gz
  sha256: 79278198d124c646b799c5e8dca8504aed9dcaaa88d071a09eb0b5c2009a58ad

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0
# Note s390x supressed because of conflicts installing test packages, and some
# breakage around ffi/cffi loading
  skip: true  # [py<38 or s390x]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.17
    - wheel
  run:
    - python
    - hatchling >=1.17

test:
  source_files:
    - .
  imports:
    - hatch_jupyter_builder
  commands:
    - pip check
    # Note windows tests supressed because of problems with utils.run(shlex.split(cmd))
    - python -m pytest -vv     # [not (win or s390x)]
  requires:
    - pip
    - pytest
    - pytest-mock
    - tomli

about:
  home: https://pypi.org/project/hatch-jupyter-builder/
  summary: A hatch plugin to help build Jupyter packages
  description: A build hook plugin for Hatch that adds a build step for use with Jupyter packages.
  dev_url: https://github.com/jupyterlab/hatch-jupyter-builder
  doc_url: https://hatch-jupyter-builder.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - blink1073
    - zsailer
