{% set name = "hatch-jupyter-builder" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_jupyter_builder-{{ version }}.tar.gz
  sha256: 0dbd14a8aef6636764f88a8fd1fcc9a91921e5c50356e6aab251782f264ae960

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python
    - hatchling >=1.0
    - wheel
  run:
    - python
    - hatchling >=1.0

test:
  source_files:
    - .
  imports:
    - hatch_jupyter_builder
  commands:
    - pip check
    - pip install -e ".[test]"
    - python -m pytest -vv
  requires:
    - pip

about:
  home: https://pypi.org/project/hatch-jupyter-builder/
  summary: A hatch plugin to help build Jupyter packages
  description: A build hook plugin for Hatch that adds a build step for use with Jupyter packages.
  dev_url: https://github.com/jupyterlab/hatch-jupyter-builder
  doc_url: https://hatch-jupyter-builder.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - blink1073
    - zsailer
