{% set name = "hatch-jupyter-builder" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_jupyter_builder-{{ version }}.tar.gz
  sha256: e28cb0b23bc4e0f845199ad649b0fb46d3393a650d4e8e3ac758a505790d8dd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.0
  run:
    - python >=3.7
    - hatchling >=1.0

test:
  imports:
    - hatch_jupyter_builder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hatch-jupyter-builder/
  summary: A hatch plugin to help build Jupyter packages
  dev_url: https://github.com/blink0173/hatch-jupyter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - blink1073
    - zsailer
